import { useEffect,useState } from 'react'
import type { FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import DatePicker from '../components/DatePicker'
import AppSelect from '../components/AppSelect'
import { createYouth,listGroups } from '../services/youth'
import type { MedicalProfile } from '../types/domain'
import { Phone,Send } from 'lucide-react'
import { listAdminUsers,saveUserPhone,sendNotice } from '../services/admin'
import type { AdminUser } from '../services/admin'

const medicalFields:[keyof Omit<MedicalProfile,'young_person_id'>,string][]=[['blood_type','Grupo sanguíneo'],['allergies','Alergias'],['medications','Medicamentos'],['medication_reason','Motivo de medicación'],['health_provider','Obra social'],['insurance_member_number','Número de afiliado'],['relevant_conditions','Condiciones relevantes'],['surgeries','Cirugías'],['activity_restrictions','Restricciones físicas'],['dietary_restrictions','Restricciones alimentarias'],['emergency_notes','Notas de emergencia']]
const value=(form:FormData,key:string)=>String(form.get(key)??'').trim()
export default function AdminPage(){
 const nav=useNavigate(),[groups,setGroups]=useState<{id:string;name:string}[]>([]),[error,setError]=useState(''),[saving,setSaving]=useState(false),[groupId,setGroupId]=useState('')
 const [users,setUsers]=useState<AdminUser[]>([]),[usersError,setUsersError]=useState(''),[noticeOpen,setNoticeOpen]=useState(false),[recipient,setRecipient]=useState('instructors'),[noticeBusy,setNoticeBusy]=useState(false),[noticeMessage,setNoticeMessage]=useState(''),[phoneEditor,setPhoneEditor]=useState<string|null>(null)
 useEffect(()=>{listGroups().then(setGroups).catch(e=>setError('No se pudieron cargar los grupos: '+e.message))},[])
 useEffect(()=>{listAdminUsers().then(setUsers).catch(e=>setUsersError('No se pudo cargar el listado: '+e.message))},[])
 async function savePhone(e:FormEvent<HTMLFormElement>,id:string){e.preventDefault();setUsersError('');const phone=value(new FormData(e.currentTarget),'phone');try{await saveUserPhone(id,phone);setUsers(old=>old.map(u=>u.id===id?{...u,phone}:u));setPhoneEditor(null)}catch(err){setUsersError('No se pudo guardar el teléfono: '+(err instanceof Error?err.message:String(err)))}}
 async function submitNotice(e:FormEvent<HTMLFormElement>){e.preventDefault();setNoticeMessage('');const form=new FormData(e.currentTarget),title=value(form,'title'),body=value(form,'body');const ids=recipient==='instructors'?users.filter(u=>u.active&&u.role==='instructor').map(u=>u.id):users.filter(u=>u.active&&u.id===recipient).map(u=>u.id);setNoticeBusy(true);try{await sendNotice(ids,title,body);setNoticeMessage(`Aviso enviado a ${ids.length} ${ids.length===1?'usuario':'usuarios'}.`);setNoticeOpen(false)}catch(err){setNoticeMessage('No se pudo enviar el aviso: '+(err instanceof Error?err.message:String(err)))}finally{setNoticeBusy(false)}}
 async function addYouth(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const form=new FormData(e.currentTarget),birth_date=value(form,'birth_date');if(!birth_date){setError('Seleccioná la fecha de nacimiento.');return}setSaving(true)
  const medical=Object.fromEntries(medicalFields.map(([key])=>[key,value(form,key)||null])) as Partial<Omit<MedicalProfile,'young_person_id'>>
  try{const id=await createYouth({first_name:value(form,'first_name'),last_name:value(form,'last_name'),birth_date,phone:value(form,'phone'),address:value(form,'address'),group_id:value(form,'group_id'),guardian_name:value(form,'guardian_name'),guardian_phone:value(form,'guardian_phone'),guardian_email:value(form,'guardian_email'),guardian_relationship:value(form,'guardian_relationship'),guardian_address:value(form,'guardian_address'),medical,photo:form.get('photo') instanceof File&&(form.get('photo') as File).size>0?form.get('photo') as File:undefined});nav('/jovenes/'+id)}catch(err){setError('No se pudo completar el alta: '+(err instanceof Error?err.message:String(err)))}finally{setSaving(false)}}
 return <><div className="page-title"><div><h1>Panel de admin</h1><span>Gestión general</span></div></div>
 <section className="admin-directory"><div className="row-between"><div><h2>Usuarios e instructores</h2><p className="muted">{users.filter(u=>u.active).length} usuarios activos</p></div><button className="small-primary" onClick={()=>{setNoticeOpen(true);setNoticeMessage('')}}><Send size={16}/> Enviar aviso</button></div>
 {usersError&&<div className="error-box" role="alert">{usersError}</div>}{noticeMessage&&<div className={noticeMessage.startsWith('No se')?'error-box':'success-box'} role="status">{noticeMessage}</div>}
 <div className="list-stack">{users.map(u=><div className="person-row admin-user" key={u.id}><div className="avatar">{u.full_name.trim().charAt(0).toUpperCase()}</div><div className="grow"><strong>{u.full_name}{!u.active?' · Inactivo':''}</strong><small>{u.role} · {u.email}</small><small>{u.phone||'Teléfono sin registrar'}</small>{phoneEditor===u.id&&<form className="phone-form" onSubmit={e=>void savePhone(e,u.id)}><input name="phone" type="tel" defaultValue={u.phone??''} placeholder="Teléfono" autoFocus/><button className="small-primary">Guardar</button><button type="button" className="text-btn" onClick={()=>setPhoneEditor(null)}>Cancelar</button></form>}</div><div className="user-actions">{u.phone&&<a className="text-btn" href={'tel:'+u.phone.replace(/[^+\d]/g,'')} aria-label={'Llamar a '+u.full_name}><Phone size={18}/></a>}<button type="button" className="text-btn" onClick={()=>setPhoneEditor(u.id)}>{u.phone?'Editar teléfono':'Agregar teléfono'}</button></div></div>)}{!usersError&&!users.length&&<div className="empty-card">No hay usuarios registrados.</div>}</div>
 </section>
 {noticeOpen&&<div className="dialog-backdrop" onClick={()=>setNoticeOpen(false)}><div className="form-card notice-dialog" role="dialog" aria-modal="true" aria-labelledby="notice-title" onClick={e=>e.stopPropagation()}><h2 id="notice-title">Enviar aviso</h2><p className="muted">Aparecerá en la sección Avisos de los destinatarios.</p><form className="form-grid" onSubmit={submitNotice}><div className="field-label span2">Destinatario<AppSelect label="Destinatario" value={recipient} onChange={setRecipient} options={[{value:'instructors',label:'Todos los instructores'},...users.filter(u=>u.active).map(u=>({value:u.id,label:u.full_name}))]}/></div><label className="span2">Título<input name="title" maxLength={100} required/></label><label className="span2">Mensaje<textarea name="body" maxLength={1000} required/></label><div className="span2 quick-grid"><button type="button" className="secondary-btn" onClick={()=>setNoticeOpen(false)}>Cancelar</button><button className="primary-btn" disabled={noticeBusy}>{noticeBusy?'Enviando…':'Enviar aviso'}</button></div></form>{noticeMessage&&<div className="error-box" role="alert">{noticeMessage}</div>}</div></div>}
 <section className="form-card"><h2>Alta de joven</h2>{error&&<div className="error-box" role="alert">{error}</div>}<form onSubmit={addYouth} className="form-grid"><h3 className="span2">Datos personales</h3><label>Nombre<input name="first_name" required/></label><label>Apellido<input name="last_name" required/></label><DatePicker name="birth_date" label="Fecha de nacimiento"/><div className="field-label">Grupo<AppSelect name="group_id" label="Grupo" value={groupId} onChange={setGroupId} options={[{value:"",label:"Sin asignar"},...groups.map(group=>({value:group.id,label:group.name}))]}/></div><label>Teléfono<input name="phone" type="tel"/></label><label className="span2">Domicilio<input name="address"/></label><label className="span2">Foto de perfil<input name="photo" type="file" accept="image/jpeg,image/png,image/webp"/></label><h3 className="span2">Tutor y contacto</h3><label>Nombre del tutor<input name="guardian_name"/></label><label>Vínculo<input name="guardian_relationship" placeholder="Madre, padre, tutor…"/></label><label>Teléfono del tutor<input name="guardian_phone" type="tel"/></label><label>Correo electrónico<input name="guardian_email" type="email"/></label><label className="span2">Domicilio del tutor<input name="guardian_address"/></label><h3 className="span2">Ficha médica</h3>{medicalFields.map(([key,label])=><label key={key} className={key==='emergency_notes'?'span2':''}>{label}<input name={key}/></label>)}<button className="primary-btn span2" disabled={saving}>{saving?'Guardando…':'Guardar joven'}</button></form></section></>
}
