import { useEffect,useState } from 'react'
import { useNavigate } from 'react-router-dom'
import TrafficLightDot from '../components/TrafficLight'
import { listAlerts } from '../services/alerts'
import type { AlertItem } from '../types/domain'
import { enablePush,listMyNotices,pushEnabledOnThisDevice } from '../services/admin'
import { BellRing } from 'lucide-react'
import type { UserNotice } from '../services/admin'
export default function AlertsPage(){const [items,setItems]=useState<AlertItem[]>([]),[notices,setNotices]=useState<UserNotice[]>([]),[error,setError]=useState(''),[noticeError,setNoticeError]=useState(''),[loading,setLoading]=useState(true),[pushStatus,setPushStatus]=useState(''),[pushEnabled,setPushEnabled]=useState(false),[pushBusy,setPushBusy]=useState(false);const nav=useNavigate();useEffect(()=>{listAlerts().then(setItems).catch(e=>setError('No se pudieron cargar las alertas: '+e.message)).finally(()=>setLoading(false));listMyNotices().then(setNotices).catch(e=>setNoticeError('No se pudieron cargar los avisos: '+e.message));pushEnabledOnThisDevice().then(setPushEnabled).catch(()=>{})},[]);async function activatePush(){setPushBusy(true);setPushStatus('');try{await enablePush();setPushEnabled(true);setPushStatus('Este teléfono ya puede recibir notificaciones push.')}catch(err){setPushStatus(err instanceof Error?err.message:String(err))}finally{setPushBusy(false)}}return <><div className="page-title"><div><h1>Alertas y avisos</h1><span>Seguimiento y mensajes para tu cuenta</span></div></div><section><div className="row-between"><h2>Avisos</h2><button className="small-primary push-activate" disabled={pushBusy} onClick={()=>void activatePush()}><BellRing size={17}/> {pushBusy?'Activando…':pushEnabled?'Actualizar notificaciones':'Activar en este teléfono'}</button></div>{pushStatus&&<div className={pushEnabled?'success-box':'error-box'} role="status">{pushStatus}</div>}{noticeError&&<div className="error-box" role="alert">{noticeError}</div>}<div className="list-stack">{notices.map(n=><div className="alert-card" key={n.id}><div className="grow"><strong>{n.title}</strong><p>{n.body}</p><small>{new Date(n.created_at).toLocaleString('es-AR')}</small></div></div>)}</div>{!noticeError&&!notices.length&&<div className="empty-card">No tenés avisos.</div>}</section><section><h2>Seguimiento de inasistencias</h2>{error&&<div className="error-box" role="alert">{error}</div>}<div className="list-stack">{items.map(a=><div className="alert-card" key={a.id}><TrafficLightDot value={a.level}/><div className="grow"><strong>{a.young_person_name}</strong><p>{a.reason}</p><small>{new Date(a.created_at).toLocaleDateString('es-AR')}</small></div><button className="small-primary" onClick={()=>nav('/jovenes/'+a.young_person_id)}>Ver perfil</button></div>)}</div>{!loading&&!error&&!items.length&&<div className="empty-card">No hay inasistencias que requieran seguimiento.</div>}</section></>}
