import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import DatePicker from '../components/DatePicker'
import TimePicker from '../components/TimePicker'
import AppSelect from '../components/AppSelect'
import { createEvent, deleteEvent, listUpcomingEvents, updateEvent } from '../services/events'
import { useAuth } from '../state/AuthContext'
import type { EventItem } from '../types/domain'

const zone='America/Argentina/Buenos_Aires'
function parts(value:string){const fields=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(value));const get=(part:string)=>fields.find(field=>field.type===part)?.value??'';return {date:[get('year'),get('month'),get('day')].join('-'),time:[get('hour'),get('minute')].join(':')}}
export default function CalendarPage(){
 const [events,setEvents]=useState<EventItem[]>([]),[adding,setAdding]=useState(false),[editing,setEditing]=useState<EventItem|null>(null),[deleting,setDeleting]=useState<string|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true),[eventKind,setEventKind]=useState<EventItem['kind']>('special')
 const [params]=useSearchParams(),{user}=useAuth(),canWrite=!!user&&(user.role==='admin'||user.role==='superadmin'||user.permissions.includes('events.write'))
 useEffect(()=>{listUpcomingEvents().then(setEvents).catch(e=>setError('No se pudo cargar el cronograma: '+e.message)).finally(()=>setLoading(false))},[])
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');const form=new FormData(e.currentTarget),date=String(form.get('date')??''),time=String(form.get('time')??'');if(!date||!time){setError('Seleccioná fecha y hora.');return}const start=new Date(date+'T'+time+':00-03:00');if(Number.isNaN(start.getTime())){setError('La fecha u hora no es válida.');return}
  const input={title:String(form.get('title')??'').trim(),kind:String(form.get('kind')) as EventItem['kind'],starts_at:start.toISOString(),location:String(form.get('location')??'').trim(),description:String(form.get('description')??'').trim()};setSaving(true)
  try{const item=editing?await updateEvent(editing.id,input):await createEvent(input);setEvents(items=>[...items.filter(other=>other.id!==item.id),item].sort((a,b)=>a.starts_at.localeCompare(b.starts_at)));setEditing(null);setAdding(false)}catch(err){setError('No se pudo guardar el evento: '+(err instanceof Error?err.message:String(err)))}finally{setSaving(false)}}
 async function remove(id:string){setError('');setSaving(true);try{await deleteEvent(id);setEvents(items=>items.filter(item=>item.id!==id));setDeleting(null)}catch(err){setError('No se pudo eliminar el evento: '+(err instanceof Error?err.message:String(err)))}finally{setSaving(false)}}
 const active=editing?parts(editing.starts_at):undefined
 return <><div className="page-title"><div><h1>Cronograma</h1><span>Clases y actividades programadas</span></div>{canWrite&&<button className="small-primary" onClick={()=>{setEditing(null);setEventKind('special');setAdding(true);setError('')}}>+ Nuevo</button>}</div>
 {error&&<div className="error-box" role="alert">{error}</div>}
 {(adding||editing)&&<form key={editing?.id??'new'} className="form-card form-grid" onSubmit={submit}><h2 className="span2">{editing?'Editar evento':'Nuevo evento'}</h2><label className="span2">Nombre del evento<input name="title" defaultValue={editing?.title??''} required autoFocus/></label><div className="field-label">Tipo<AppSelect name="kind" label="Tipo de evento" value={eventKind} onChange={value=>setEventKind(value as EventItem['kind'])} options={[{value:"sunday",label:"Reunión GI"},{value:"rehearsal",label:"Ensayo"},{value:"class",label:"Clase"},{value:"meeting",label:"Reunión"},{value:"special",label:"Actividad especial"},{value:"camp",label:"Campamento"},{value:"other",label:"Otro"}]}/></div><DatePicker name="date" label="Fecha" initialValue={active?.date}/><TimePicker name="time" label="Hora" initialValue={active?.time}/><label>Lugar<input name="location" defaultValue={editing?.location??''}/></label><label className="span2">Descripción<textarea name="description" defaultValue={editing?.description??''}/></label><div className="span2 quick-grid"><button type="button" className="secondary-btn" onClick={()=>{setAdding(false);setEditing(null)}}>Cancelar</button><button className="primary-btn" disabled={saving}>{saving?'Guardando…':editing?'Guardar cambios':'Crear evento'}</button></div></form>}
 <div className="timeline">{events.map(event=><div id={'evento-'+event.id} className={'timeline-item '+(params.get('evento')===event.id?'selected-event':'')} key={event.id}><div className="event-date">{new Date(event.starts_at).toLocaleDateString('es-AR',{day:'numeric',timeZone:zone})}</div><div className="grow"><strong>{event.title}</strong><p>{new Date(event.starts_at).toLocaleString('es-AR',{dateStyle:'full',timeStyle:'short',timeZone:zone})}</p>{event.location&&<small>{event.location}</small>}{event.description&&<p>{event.description}</p>}{canWrite&&<div className="event-actions"><button type="button" className="text-btn" onClick={()=>{setAdding(false);setEditing(event);setEventKind(event.kind);setDeleting(null);setError('');window.scrollTo({top:0,behavior:'smooth'})}}>Editar</button><button type="button" className="text-btn danger-text" onClick={()=>setDeleting(event.id)}>Eliminar</button></div>}{deleting===event.id&&<div className="delete-confirm"><p>¿Eliminar este evento? Esta acción no se puede deshacer.</p><button type="button" className="text-btn" onClick={()=>setDeleting(null)}>Cancelar</button><button type="button" className="small-primary" disabled={saving} onClick={()=>remove(event.id)}>Confirmar eliminación</button></div>}</div></div>)}</div>
 {!loading&&!events.length&&<div className="empty-card">No hay eventos próximos. {canWrite?'Tocá «+ Nuevo» para agregar uno.':''}</div>}</>
}
