import { FormEvent,useCallback,useEffect,useState } from 'react'
import { ArrowLeft,Pencil,Trash2 } from 'lucide-react'
import { useNavigate,useParams } from 'react-router-dom'
import { addProjectTask,deleteProject,listProjects,listStaff,updateProject,updateProjectStatus,updateProjectTask,updateProjectTaskDetails } from '../services/projects'
import { instructors } from '../data/mock'
import type { Project,ProjectTask } from '../types/domain'
import { USE_MOCKS } from '../lib/config'
import { localDate } from '../services/attendance'
import DatePicker from '../components/DatePicker'
import AppSelect from '../components/AppSelect'

const taskStatuses=[{value:'pending',label:'Pendiente'},{value:'in_progress',label:'En curso'},{value:'blocked',label:'Bloqueada'},{value:'done',label:'Terminada'}]
const projectStatuses=[{value:'planned',label:'Planificado'},{value:'active',label:'En curso'},{value:'completed',label:'Finalizado'},{value:'cancelled',label:'Cancelado'}]
function dateLabel(value?:string){if(!value)return 'Sin fecha';const [year,month,day]=value.split('-');return day+'/'+month+'/'+year}
const field=(form:FormData,name:string)=>String(form.get(name)??'').trim()
export default function ProjectDetailPage(){
 const {id=''}=useParams(),nav=useNavigate()
 const [p,setP]=useState<Project|null>(null),[staff,setStaff]=useState<{id:string;full_name:string}[]>([])
 const [adding,setAdding]=useState(false),[editingProject,setEditingProject]=useState(false),[editingTask,setEditingTask]=useState<string|null>(null)
 const [owner,setOwner]=useState(''),[projectStatus,setProjectStatus]=useState<Project['status']>('planned'),[newAssignee,setNewAssignee]=useState(''),[taskAssignee,setTaskAssignee]=useState('')
 const [saving,setSaving]=useState(false),[confirmDelete,setConfirmDelete]=useState(false),[deleting,setDeleting]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const refresh=useCallback(async()=>{const projects=await listProjects();setP(projects.find(project=>project.id===id)??null)},[id])
 useEffect(()=>{setLoading(true);Promise.all([refresh(),listStaff()]).then(([,people])=>setStaff(people)).catch(e=>setError('No se pudo cargar el tablero: '+e.message)).finally(()=>setLoading(false))},[refresh])
 const assignees=USE_MOCKS?instructors.map(name=>({value:name,label:name})):staff.map(person=>({value:person.id,label:person.full_name}))
 const assigneeOptions=[{value:'',label:'Sin asignar'},...assignees]
 async function addTask(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError('');const d=new FormData(e.currentTarget);try{await addProjectTask(id,{title:field(d,'title'),description:field(d,'description'),due_date:field(d,'due_date'),assignee_id:field(d,'assignee_id'),weight:Number(d.get('weight'))||1});await refresh();setAdding(false);setNewAssignee('')}catch(err){setError(err instanceof Error?err.message:'No se pudo guardar la tarea.')}finally{setSaving(false)}}
 async function saveProject(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError('');const d=new FormData(e.currentTarget),start=field(d,'start_date'),end=field(d,'end_date');if(start&&end&&end<start){setError('El fin previsto debe ser posterior al inicio.');setSaving(false);return}try{await updateProject(id,{name:field(d,'name'),description:field(d,'description'),start_date:start,end_date:end,owner_user_id:field(d,'owner_user_id'),status:field(d,'status') as Project['status']});await refresh();setEditingProject(false)}catch(err){setError(err instanceof Error?err.message:'No se pudo actualizar el proyecto.')}finally{setSaving(false)}}
 async function saveTask(e:FormEvent<HTMLFormElement>,taskId:string){e.preventDefault();setSaving(true);setError('');const d=new FormData(e.currentTarget);try{await updateProjectTaskDetails(taskId,{title:field(d,'title'),description:field(d,'description'),due_date:field(d,'due_date'),weight:Number(d.get('weight'))||1,assignee_id:field(d,'assignee_id')});await refresh();setEditingTask(null)}catch(err){setError(err instanceof Error?err.message:'No se pudo actualizar la tarea.')}finally{setSaving(false)}}
 async function changeTask(taskId:string,status:ProjectTask['status']){setError('');try{await updateProjectTask(taskId,{status});await refresh()}catch(err){setError(err instanceof Error?err.message:'No se pudo actualizar la tarea.')}}
 async function changeStatus(status:Project['status']){setError('');try{await updateProjectStatus(id,status);await refresh()}catch(err){setError(err instanceof Error?err.message:'No se pudo actualizar el proyecto.')}}
 async function removeProject(){setDeleting(true);setError('');try{await deleteProject(id);nav('/proyectos',{replace:true})}catch(err){setError(err instanceof Error?err.message:'No se pudo eliminar el proyecto.');setConfirmDelete(false)}finally{setDeleting(false)}}
 if(loading)return <div className="center-screen">Cargando proyecto…</div>
 if(!p)return <><button className="icon-btn" onClick={()=>nav('/proyectos')}><ArrowLeft/></button>{error&&<div className="error-box">{error}</div>}<p>Proyecto no encontrado.</p></>
 const today=localDate(new Date().toISOString()),unfinished=p.tasks.filter(task=>task.status!=='done')
 const overdue=unfinished.filter(task=>task.due_date&&task.due_date<today)
 const blocked=unfinished.filter(task=>task.status==='blocked')
 const next=unfinished.filter(task=>task.due_date).sort((a,b)=>(a.due_date??'').localeCompare(b.due_date??''))[0]
 return <><div className="profile-head"><button className="icon-btn" onClick={()=>nav('/proyectos')}><ArrowLeft/></button><span>Tablero del proyecto</span><span/></div>{error&&<div className="error-box" role="alert">{error}</div>}
 <div className="project-detail-heading"><h1>{p.name}</h1><button type="button" className="text-btn" onClick={()=>{setEditingProject(true);setOwner(p.owner_user_id??'');setProjectStatus(p.status);setError('')}}><Pencil size={17}/> Editar proyecto</button></div>
 {p.description&&<p>{p.description}</p>}
 {editingProject&&<form className="form-card form-grid project-edit" onSubmit={saveProject}><h2 className="span2">Editar proyecto</h2><label className="span2">Nombre<input name="name" required defaultValue={p.name}/></label><label className="span2">Descripción<textarea name="description" defaultValue={p.description??''}/></label><DatePicker name="start_date" label="Inicio" initialValue={p.start_date}/><DatePicker name="end_date" label="Fin previsto" initialValue={p.end_date}/><div className="field-label">Responsable general<AppSelect name="owner_user_id" label="Responsable general" value={owner} onChange={setOwner} options={assigneeOptions}/></div><div className="field-label">Estado<AppSelect name="status" label="Estado del proyecto" value={projectStatus} onChange={value=>setProjectStatus(value as Project['status'])} options={projectStatuses}/></div><div className="span2 quick-grid"><button type="button" className="secondary-btn" onClick={()=>setEditingProject(false)}>Cancelar</button><button className="primary-btn" disabled={saving}>{saving?'Guardando…':'Guardar cambios'}</button></div></form>}
 <div className="detail-card project-summary"><div><span>Responsable general</span><strong>{p.owner}</strong></div><div><span>Inicio</span><strong>{dateLabel(p.start_date)}</strong></div><div><span>Fin previsto</span><strong>{dateLabel(p.end_date)}</strong></div><div><span>Estado</span><AppSelect label="Estado del proyecto" value={p.status} onChange={value=>void changeStatus(value as Project['status'])} options={projectStatuses}/></div></div>
 <div className="big-progress" role="progressbar" aria-label="Avance del proyecto" aria-valuenow={p.progress} aria-valuemin={0} aria-valuemax={100}><span style={{width:p.progress+'%'}}/><b>{p.progress}%</b></div>
 <div className="project-metrics"><div className="project-metric"><strong>{p.tasks.filter(task=>task.status==='done').length}/{p.tasks.length}</strong><small>Tareas terminadas</small></div><div className="project-metric warn"><strong>{blocked.length}</strong><small>Bloqueadas</small></div><div className="project-metric alert"><strong>{overdue.length}</strong><small>Vencidas</small></div></div>
 <div className="project-focus"><h2>Próximo paso</h2>{next?<p><strong>{next.title}</strong> · {overdue.some(task=>task.id===next.id)?'Vencida el':'Límite'} {dateLabel(next.due_date)} · {next.assignee}</p>:<p>{p.tasks.length?'No quedan tareas con fecha pendiente.':'Agregá una tarea con responsable y fecha límite para empezar el seguimiento.'}</p>}</div>
 <section><div className="row-between"><h2>Tareas</h2><button className="small-primary" onClick={()=>setAdding(true)}>+ Tarea</button></div>
 {adding&&<form className="form-card form-grid" onSubmit={addTask}><label className="span2">Tarea<input name="title" autoFocus required/></label><label className="span2">Detalle<textarea name="description"/></label><div className="field-label">Responsable<AppSelect name="assignee_id" label="Responsable" value={newAssignee} onChange={setNewAssignee} options={assigneeOptions}/></div><DatePicker name="due_date" label="Fecha límite"/><label>Peso en el avance<input name="weight" type="number" min="0.01" step="0.01" defaultValue="1" required/></label><div className="span2 quick-grid"><button type="button" className="secondary-btn" onClick={()=>setAdding(false)}>Cancelar</button><button className="primary-btn" disabled={saving}>{saving?'Guardando…':'Guardar tarea'}</button></div></form>}
 {p.tasks.length===0?<p>Todavía no hay tareas. Agregá la primera para comenzar el seguimiento.</p>:<div className="list-stack">{p.tasks.map(task=><div className="task-row" key={task.id}><div><strong>{task.title}</strong>{task.description&&<small>{task.description}</small>}<small>{task.assignee} · Límite: {dateLabel(task.due_date)} · Peso: {task.weight}</small>{task.status!=='done'&&task.due_date&&task.due_date<today&&<small className="danger-text">Plazo vencido</small>}<div className="task-edit-actions"><button type="button" className="text-btn" onClick={()=>{setEditingTask(task.id);setTaskAssignee(task.assignee_id??'');setError('')}}>Editar tarea</button></div></div><AppSelect label={'Estado de '+task.title} value={task.status} onChange={value=>void changeTask(task.id,value as ProjectTask['status'])} options={taskStatuses} className={'task-status-control '+task.status}/>{editingTask===task.id&&<form key={task.id} className="form-card form-grid span2" onSubmit={event=>saveTask(event,task.id)}><label className="span2">Tarea<input name="title" defaultValue={task.title} required/></label><label className="span2">Detalle<textarea name="description" defaultValue={task.description??''}/></label><div className="field-label">Responsable<AppSelect name="assignee_id" label="Responsable" value={taskAssignee} onChange={setTaskAssignee} options={assigneeOptions}/></div><DatePicker name="due_date" label="Fecha límite" initialValue={task.due_date}/><label>Peso en el avance<input name="weight" type="number" min="0.01" step="0.01" defaultValue={task.weight} required/></label><div className="span2 quick-grid"><button type="button" className="secondary-btn" onClick={()=>setEditingTask(null)}>Cancelar</button><button className="primary-btn" disabled={saving}>{saving?'Guardando…':'Guardar tarea'}</button></div></form>}</div>)}</div>}</section>
 <section className="project-delete-section">{confirmDelete?<div className="project-delete-confirm" role="group" aria-label="Confirmar eliminación del proyecto"><strong>¿Eliminar «{p.name}»?</strong><p>También se eliminarán sus {p.tasks.length} tareas. Esta acción no se puede deshacer.</p><div className="quick-grid"><button className="secondary-btn" onClick={()=>setConfirmDelete(false)} disabled={deleting}>Cancelar</button><button className="danger-btn" onClick={removeProject} disabled={deleting}>{deleting?'Eliminando…':'Sí, eliminar'}</button></div></div>:<button className="delete-link" onClick={()=>setConfirmDelete(true)}><Trash2 size={18}/> Eliminar proyecto</button>}</section></>
}
