import { FormEvent,useCallback,useEffect,useState } from 'react'
import { ArrowLeft } from 'lucide-react'
import { useNavigate,useParams } from 'react-router-dom'
import { addProjectTask,listProjects,listStaff,updateProjectStatus,updateProjectTask } from '../services/projects'
import { instructors } from '../data/mock'
import type { Project } from '../types/domain'
import { USE_MOCKS } from '../lib/config'
import DatePicker from '../components/DatePicker'

const statuses={pending:'Pendiente',in_progress:'En curso',blocked:'Bloqueada',done:'Terminada'}
function dateLabel(value?:string){if(!value)return 'Sin fecha';const [year,month,day]=value.split('-');return `${day}/${month}/${year}`}
export default function ProjectDetailPage(){
 const {id=''}=useParams(),nav=useNavigate();const [p,setP]=useState<Project|null>(null),[staff,setStaff]=useState<{id:string;full_name:string}[]>([]),[adding,setAdding]=useState(false),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const refresh=useCallback(async()=>{const projects=await listProjects();setP(projects.find(x=>x.id===id)??null)},[id])
 useEffect(()=>{setLoading(true);Promise.all([refresh(),listStaff()]).then(([,people])=>setStaff(people)).catch(e=>setError(`No se pudo cargar el tablero: ${e.message}`)).finally(()=>setLoading(false))},[refresh])
 async function addTask(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError('');const d=new FormData(e.currentTarget);try{await addProjectTask(id,{title:String(d.get('title')).trim(),description:String(d.get('description')).trim(),due_date:String(d.get('due_date')),assignee_id:String(d.get('assignee_id')),weight:Number(d.get('weight'))||1});await refresh();setAdding(false)}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar la tarea.')}finally{setSaving(false)}}
 async function changeTask(taskId:string,status:Project['tasks'][number]['status']){setError('');try{await updateProjectTask(taskId,{status});await refresh()}catch(e){setError(e instanceof Error?e.message:'No se pudo actualizar la tarea.')}}
 async function changeStatus(status:Project['status']){setError('');try{await updateProjectStatus(id,status);await refresh()}catch(e){setError(e instanceof Error?e.message:'No se pudo actualizar el proyecto.')}}
 if(loading)return <div className="center-screen">Cargando proyecto…</div>
 return <><div className="profile-head"><button className="icon-btn" onClick={()=>nav('/proyectos')}><ArrowLeft/></button><span>Tablero del proyecto</span><span/></div>{error&&<div className="error-box" role="alert">{error}</div>}{!p?<p>Proyecto no encontrado.</p>:<><h1>{p.name}</h1>{p.description&&<p>{p.description}</p>}<div className="detail-card project-summary"><div><span>Responsable general</span><strong>{p.owner}</strong></div><div><span>Inicio</span><strong>{dateLabel(p.start_date)}</strong></div><div><span>Fin previsto</span><strong>{dateLabel(p.end_date)}</strong></div><div><span>Estado</span><select aria-label="Estado del proyecto" value={p.status} onChange={e=>void changeStatus(e.target.value as Project['status'])}><option value="planned">Planificado</option><option value="active">En curso</option><option value="completed">Finalizado</option><option value="cancelled">Cancelado</option></select></div></div><div className="big-progress"><span style={{width:`${p.progress}%`}}/><b>{p.progress}%</b></div><p>{p.tasks.filter(t=>t.status==='done').length} de {p.tasks.length} tareas terminadas</p><section><div className="row-between"><h2>Tareas</h2><button className="small-primary" onClick={()=>setAdding(true)}>+ Tarea</button></div>{adding&&<form className="form-card form-grid" onSubmit={addTask}><label className="span2">Tarea<input name="title" placeholder="Descripción de la tarea" autoFocus required/></label><label className="span2">Detalle<textarea name="description"/></label><label>Responsable<select name="assignee_id"><option value="">Sin asignar</option>{USE_MOCKS?instructors.map(name=><option key={name} value={name}>{name}</option>):staff.map(person=><option key={person.id} value={person.id}>{person.full_name}</option>)}</select></label><DatePicker name="due_date" label="Fecha límite"/><label>Peso en el avance<input name="weight" type="number" min="0.01" step="0.01" defaultValue="1" required/></label><div className="span2 quick-grid"><button type="button" className="secondary-btn" onClick={()=>setAdding(false)}>Cancelar</button><button className="primary-btn" disabled={saving}>{saving?'Guardando…':'Guardar tarea'}</button></div></form>}{p.tasks.length===0?<p>Todavía no hay tareas. Agregá la primera para comenzar el seguimiento.</p>:<div className="list-stack">{p.tasks.map(t=><div className="task-row" key={t.id}><div><strong>{t.title}</strong>{t.description&&<small>{t.description}</small>}<small>{t.assignee} · Límite: {dateLabel(t.due_date)} · Peso: {t.weight}</small></div><select aria-label={`Estado de ${t.title}`} className={`task-status ${t.status}`} value={t.status} onChange={e=>void changeTask(t.id,e.target.value as typeof t.status)}>{Object.entries(statuses).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div>)}</div>}</section></>}</>
}
