import { FormEvent,useEffect,useState } from 'react'
import { ArrowLeft,Pencil,Phone } from 'lucide-react'
import { useNavigate,useParams } from 'react-router-dom'
import TrafficLightDot from '../components/TrafficLight'
import { getMedicalProfile,getYouth,updateYouth } from '../services/youth'
import type { MedicalProfile,YoungPerson } from '../types/domain'
function age(s:string){const d=new Date(s),n=new Date();let a=n.getFullYear()-d.getFullYear();if(n<new Date(n.getFullYear(),d.getMonth(),d.getDate()))a--;return a}
export default function YouthProfilePage(){
 const {id=''}=useParams(),nav=useNavigate();const [y,setY]=useState<YoungPerson|null>(null),[medical,setMedical]=useState<MedicalProfile|null>(null),[medicalError,setMedicalError]=useState(''),[editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[notice,setNotice]=useState('');useEffect(()=>{getYouth(id).then(setY).catch(()=>setNotice('No se pudo cargar el perfil del joven.'));getMedicalProfile(id).then(setMedical).catch(()=>setMedicalError('No se pudo cargar la ficha médica.'))},[id]);if(!y)return <div className="center-screen">{notice||'Cargando perfil…'}</div>
 const medicalFields:[string,string|null][]=[['Alergias',medical?.allergies??null],['Grupo sanguíneo',medical?.blood_type??null],['Obra social',medical?.health_provider??null],['Número de afiliado',medical?.insurance_member_number??null],['Medicamentos',medical?.medications??null],['Motivo de medicación',medical?.medication_reason??null],['Condiciones relevantes',medical?.relevant_conditions??null],['Cirugías',medical?.surgeries??null],['Restricciones físicas',medical?.activity_restrictions??null],['Restricciones alimentarias',medical?.dietary_restrictions??null],['Notas de emergencia',medical?.emergency_notes??null]]
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setNotice('');const data=new FormData(e.currentTarget);try{const updated=await updateYouth(id,{first_name:String(data.get('first_name')),last_name:String(data.get('last_name')),birth_date:String(data.get('birth_date')),phone:String(data.get('phone')),address:String(data.get('address'))});setY({...y,...updated});setEditing(false);setNotice('Perfil actualizado.')}catch{setNotice('No se pudo guardar el perfil.')}finally{setSaving(false)}}
 const call=()=>{if(!y.guardian_phone){setNotice('No hay teléfono del responsable registrado todavía.');return}window.location.href=`tel:${y.guardian_phone}`}
 return <><div className="profile-head"><button className="icon-btn" onClick={()=>nav(-1)}><ArrowLeft/></button><span>Perfil del joven</span><button aria-label="Editar perfil" className="icon-btn" onClick={()=>setEditing(v=>!v)}><Pencil size={18}/></button></div><div className="profile-avatar">{y.first_name[0]}{y.last_name[0]}</div><h1 className="profile-name">{y.first_name} {y.last_name}</h1><p className="profile-sub">{age(y.birth_date)} años · {y.group_name??'Sin grupo asignado'}</p>
 <div className="profile-stats"><div><span>Asistencia</span><strong className="good">{y.attendance_rate}%</strong></div><div><span>Domingos</span><strong>{y.sundays}</strong></div><div><span>Ensayos</span><strong>{y.rehearsals}</strong></div><div><span>Semáforo</span><TrafficLightDot value={y.traffic_light}/></div></div>
 {editing?<section className="form-card"><h2>Editar perfil</h2><form onSubmit={save} className="form-grid"><label>Nombre<input name="first_name" defaultValue={y.first_name} required/></label><label>Apellido<input name="last_name" defaultValue={y.last_name} required/></label><label>Fecha de nacimiento<input name="birth_date" type="date" defaultValue={y.birth_date} required/></label><label>Teléfono<input name="phone" defaultValue={y.phone??''}/></label><label className="span2">Dirección<input name="address" defaultValue={y.address??''}/></label><div className="span2 quick-grid"><button type="button" className="secondary-btn" onClick={()=>setEditing(false)}>Cancelar</button><button className="primary-btn" disabled={saving}>{saving?'Guardando…':'Guardar cambios'}</button></div></form></section>:<section><h2>Datos personales</h2><div className="detail-card"><div><span>Fecha de nacimiento</span><strong>{new Date(y.birth_date).toLocaleDateString('es-AR')}</strong></div><div><span>Teléfono</span><strong>{y.phone??'Sin registrar'}</strong></div><div><span>Grupo</span><strong>{y.group_name??'Sin asignar'}</strong></div><div><span>Dirección</span><strong>{y.address??'Sin registrar'}</strong></div></div></section>}
 <section><h2>Ficha médica</h2>{medicalError?<div className="error-box">{medicalError}</div>:medical?<div className="detail-card medical">{medicalFields.map(([label,value])=><div key={label}><span>{label}</span><strong>{value||'Sin registrar'}</strong></div>)}</div>:<div className="detail-card medical"><div><span>Ficha</span><strong>Sin datos registrados</strong></div></div>}</section>
 <section><h2>Últimas 8 semanas</h2><div className="weeks-card">{['P','P','P','A','P','P','P','P'].map((v,i)=><div key={i}><span className={`week-dot ${v==='P'?'present':'absent'}`}/><small>{v}</small></div>)}</div></section>
 <div className="quick-grid"><button className="secondary-btn" onClick={call}><Phone size={18}/> Llamar a tutor</button><button className="secondary-btn" onClick={()=>setEditing(true)}><Pencil size={18}/> Editar perfil</button></div>{notice&&<div className="success-box">{notice}</div>}</>
}
