import { FormEvent,useEffect,useRef,useState } from 'react'
import { ArrowLeft,Camera,Pencil,Phone,X } from 'lucide-react'
import { useNavigate,useParams } from 'react-router-dom'
import TrafficLightDot from '../components/TrafficLight'
import DatePicker from '../components/DatePicker'
import { getMedicalProfile,getYouth,getYouthPhoto,updateGuardianPhone,updateYouth,uploadYouthPhoto } from '../services/youth'
import type { MedicalProfile,YoungPerson } from '../types/domain'
function age(s:string){const d=new Date(s),n=new Date();let a=n.getFullYear()-d.getFullYear();if(n<new Date(n.getFullYear(),d.getMonth(),d.getDate()))a--;return a}
function editName(y:YoungPerson){if(y.last_name?.trim())return {first:y.first_name,last:y.last_name};const parts=y.first_name.trim().split(/\s+/);return parts.length>1?{first:parts.slice(1).join(' '),last:parts[0]}:{first:y.first_name,last:''}}
function cleanPhone(value?:string){return (value??'').replace(/\.0$/,'')}
export default function YouthProfilePage(){
 const {id=''}=useParams(),nav=useNavigate();const [y,setY]=useState<YoungPerson|null>(null),[medical,setMedical]=useState<MedicalProfile|null>(null),[medicalError,setMedicalError]=useState(''),[editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[notice,setNotice]=useState(''),[formError,setFormError]=useState(''),[photoUrl,setPhotoUrl]=useState<string|null>(null),[selectedPhoto,setSelectedPhoto]=useState<File|null>(null),[previewUrl,setPreviewUrl]=useState<string|null>(null);const editRef=useRef<HTMLElement>(null),photoInputRef=useRef<HTMLInputElement>(null);useEffect(()=>{getYouth(id).then(setY).catch(()=>setNotice('No se pudo cargar el perfil del joven.'));getMedicalProfile(id).then(setMedical).catch(()=>setMedicalError('No se pudo cargar la ficha médica.'))},[id]);useEffect(()=>{let active=true;getYouthPhoto(y?.photo_path).then(url=>{if(active)setPhotoUrl(url)}).catch(error=>{if(active)setNotice(`No se pudo cargar la foto: ${error instanceof Error?error.message:'error desconocido'}`)});return()=>{active=false}},[y?.photo_path]);useEffect(()=>{if(!selectedPhoto){setPreviewUrl(null);return}const url=URL.createObjectURL(selectedPhoto);setPreviewUrl(url);return()=>URL.revokeObjectURL(url)},[selectedPhoto]);useEffect(()=>{if(editing)requestAnimationFrame(()=>editRef.current?.scrollIntoView({behavior:'smooth',block:'start'}))},[editing]);if(!y)return <div className="center-screen">{notice||'Cargando perfil…'}</div>
 const medicalFields:[string,string|null][]=[['Alergias',medical?.allergies??null],['Grupo sanguíneo',medical?.blood_type??null],['Obra social',medical?.health_provider??null],['Número de afiliado',medical?.insurance_member_number??null],['Medicamentos',medical?.medications??null],['Motivo de medicación',medical?.medication_reason??null],['Condiciones relevantes',medical?.relevant_conditions??null],['Cirugías',medical?.surgeries??null],['Restricciones físicas',medical?.activity_restrictions??null],['Restricciones alimentarias',medical?.dietary_restrictions??null],['Notas de emergencia',medical?.emergency_notes??null]]
 const name=editName(y)
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setNotice('');setFormError('');const data=new FormData(e.currentTarget);try{if(!data.get('birth_date'))throw new Error('Seleccioná la fecha de nacimiento.');const photoPath=selectedPhoto?await uploadYouthPhoto(id,selectedPhoto):y?.photo_path;const updated=await updateYouth(id,{photo_path:photoPath,first_name:String(data.get('first_name')),last_name:String(data.get('last_name')),birth_date:String(data.get('birth_date')),phone:String(data.get('phone')),address:String(data.get('address'))});setY({...y,...updated});if(selectedPhoto){const signedUrl=await getYouthPhoto(photoPath);if(!signedUrl)throw new Error('La foto se guardó, pero no se pudo abrir. Revisá los permisos del almacenamiento.');setPhotoUrl(signedUrl)}await updateGuardianPhone(id,String(data.get('guardian_name')).trim(),String(data.get('guardian_phone')).trim());setY(current=>current?{...current,guardian_name:String(data.get('guardian_name')).trim(),guardian_phone:String(data.get('guardian_phone')).trim()}:current);setSelectedPhoto(null);setEditing(false);setNotice('Perfil actualizado.')}catch(error){setFormError(error&&typeof error==='object'&&'message' in error?String(error.message):'No se pudo guardar el perfil.')}finally{setSaving(false)}}
 const openEditor=()=>{setEditing(true);setFormError('');if(editing)editRef.current?.scrollIntoView({behavior:'smooth',block:'start'})}
 const call=()=>{if(!y.guardian_phone){setNotice('No hay teléfono del responsable registrado todavía.');return}window.location.href=`tel:${y.guardian_phone}`}
 return <><div className="profile-head"><button className="icon-btn" onClick={()=>nav(-1)}><ArrowLeft/></button><span>Perfil del joven</span><button type="button" aria-label={editing?'Cerrar edición sin guardar':'Editar perfil'} className="icon-btn" onClick={()=>{if(editing){setEditing(false);setSelectedPhoto(null);setFormError('')}else openEditor()}}>{editing?<X size={18}/>:<Pencil size={18}/>}</button></div><div className="profile-avatar">{(previewUrl||photoUrl)?<img src={previewUrl||photoUrl||''} alt={`Foto de ${y.first_name}`} />:<>{y.first_name[0]}{y.last_name[0]}</>}</div><h1 className="profile-name">{y.first_name} {y.last_name}</h1><p className="profile-sub">{age(y.birth_date)} años · {y.group_name??'Sin grupo asignado'}</p>
 <div className="profile-stats"><div><span>Asistencia</span><strong className="good">{y.attendance_rate}%</strong></div><div><span>Domingos</span><strong>{y.sundays}</strong></div><div><span>Ensayos</span><strong>{y.rehearsals}</strong></div><div><span>Semáforo</span><TrafficLightDot value={y.traffic_light}/></div></div>
 {editing?<section className="form-card profile-editor" ref={editRef}><div className="row-between"><h2>Editar perfil</h2><button type="button" className="text-btn" onClick={()=>{setEditing(false);setSelectedPhoto(null);setFormError('')}}>Cerrar sin guardar</button></div><form onSubmit={save} className="form-grid">{!y.last_name?.trim()&&<p className="span2 field-hint">Revisá nombre y apellido: este perfil llegó con ambos en un solo campo.</p>}<label>Nombre<input name="first_name" defaultValue={name.first} required/></label><label>Apellido<input name="last_name" defaultValue={name.last} required/></label><DatePicker name="birth_date" label="Fecha de nacimiento" initialValue={y.birth_date}/><label>Teléfono<input name="phone" type="tel" defaultValue={cleanPhone(y.phone)}/></label><label>Nombre del tutor<input name="guardian_name" defaultValue={y.guardian_name??''}/></label><label>Teléfono del tutor<input name="guardian_phone" type="tel" defaultValue={cleanPhone(y.guardian_phone)}/></label><div className="span2 photo-field"><span>Foto de perfil</span><input ref={photoInputRef} className="photo-file-input" name="photo" type="file" accept="image/*" aria-label="Seleccionar foto de perfil" onChange={e=>setSelectedPhoto(e.target.files?.[0]??null)}/><button type="button" className="photo-picker" onClick={()=>photoInputRef.current?.click()}><Camera size={20}/> {selectedPhoto?'Cambiar foto':'Elegir foto'}</button><small>{selectedPhoto?`${selectedPhoto.name} · Vista previa, aún sin guardar`:'Imagen JPG, PNG o WebP · hasta 5 MB'}</small></div><label className="span2">Dirección<input name="address" defaultValue={y.address??''}/></label>{formError&&<div className="span2 error-box" role="alert">{formError}</div>}<div className="span2 quick-grid"><button type="button" className="secondary-btn" onClick={()=>{setSelectedPhoto(null);setFormError('');setEditing(false)}}>Cancelar</button><button className="primary-btn" disabled={saving}>{saving?'Guardando…':'Guardar cambios'}</button></div></form></section>:<section><h2>Datos personales</h2><div className="detail-card"><div><span>Fecha de nacimiento</span><strong>{new Date(y.birth_date).toLocaleDateString('es-AR')}</strong></div><div><span>Teléfono</span><strong>{cleanPhone(y.phone)||'Sin registrar'}</strong></div><div><span>Tutor</span><strong>{y.guardian_name||'Sin registrar'}</strong></div><div><span>Teléfono del tutor</span><strong>{cleanPhone(y.guardian_phone)||'Sin registrar'}</strong></div><div><span>Grupo</span><strong>{y.group_name??'Sin asignar'}</strong></div><div><span>Dirección</span><strong>{y.address??'Sin registrar'}</strong></div></div></section>}
 <section><h2>Ficha médica</h2>{medicalError?<div className="error-box">{medicalError}</div>:medical?<div className="detail-card medical">{medicalFields.map(([label,value])=><div key={label}><span>{label}</span><strong>{value||'Sin registrar'}</strong></div>)}</div>:<div className="detail-card medical"><div><span>Ficha</span><strong>Sin datos registrados</strong></div></div>}</section>
 <section><h2>Últimas 8 semanas</h2><div className="weeks-card">{['P','P','P','A','P','P','P','P'].map((v,i)=><div key={i}><span className={`week-dot ${v==='P'?'present':'absent'}`}/><small>{v}</small></div>)}</div></section>
 <div className="quick-grid"><button className="secondary-btn" onClick={call}><Phone size={18}/> Llamar a tutor</button><button className="secondary-btn" onClick={openEditor}><Pencil size={18}/> Editar perfil</button></div>{notice&&<div className="success-box">{notice}</div>}</>
}
