import { useEffect,useRef,useState } from 'react'
import { Check,ChevronDown } from 'lucide-react'

export type SelectOption={value:string;label:string}
type Props={value:string;options:SelectOption[];onChange:(value:string)=>void;label:string;name?:string;className?:string;disabled?:boolean}
export default function AppSelect({value,options,onChange,label,name,className='',disabled=false}:Props){
 const [open,setOpen]=useState(false),[above,setAbove]=useState(false),root=useRef<HTMLDivElement>(null)
 useEffect(()=>{if(open)root.current?.querySelector<HTMLButtonElement>('[role="option"][aria-selected="true"]')?.focus()},[open])
 useEffect(()=>{if(!open)return;const rect=root.current?.getBoundingClientRect();setAbove(!!rect&&window.innerHeight-rect.bottom<Math.min(options.length*48+20,320)&&rect.top>Math.min(options.length*48+20,320));function close(event:PointerEvent){if(!root.current?.contains(event.target as Node))setOpen(false)}function escape(event:KeyboardEvent){if(event.key==='Escape'){setOpen(false);root.current?.querySelector<HTMLButtonElement>('.app-select-trigger')?.focus()}}document.addEventListener('pointerdown',close);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',escape)}},[open,options.length])
 const selected=options.find(option=>option.value===value)
 return <div className={'app-select '+className} ref={root}>{name&&<input type="hidden" name={name} value={value}/>}<button type="button" className="app-select-trigger" aria-label={label+': '+(selected?.label??'Sin asignar')} aria-haspopup="listbox" aria-expanded={open} disabled={disabled} onClick={()=>setOpen(current=>!current)} onKeyDown={event=>{if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();setOpen(true)}}}><span>{selected?.label??'Sin asignar'}</span><ChevronDown size={18}/></button>{open&&<div className={'app-select-menu '+(above?'above':'')} role="listbox" aria-label={label}>{options.map(option=><button type="button" key={option.value} role="option" aria-selected={option.value===value} className={option.value===value?'selected':''} onClick={()=>{onChange(option.value);setOpen(false)}} onKeyDown={event=>{if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();const buttons=Array.from(root.current?.querySelectorAll<HTMLButtonElement>('[role="option"]')??[]),index=buttons.indexOf(event.currentTarget);buttons[(index+(event.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus()}}}><span>{option.label}</span>{option.value===value&&<Check size={17}/>}</button>)}</div>}</div>
}
