create or replace function public.has_role(roles public.app_role[]) returns boolean language sql stable security definer set search_path=public as $$
select exists(select 1 from public.app_users where id=auth.uid() and active=true and role=any(roles)) $$;
create or replace function public.has_permission(p text) returns boolean language sql stable security definer set search_path=public as $$
select exists(select 1 from public.app_users where id=auth.uid() and active=true and (role in ('superadmin','admin') or p=any(permissions))) $$;

alter table public.app_users enable row level security;
alter table public.young_people enable row level security;
alter table public.guardians enable row level security;
alter table public.young_person_guardians enable row level security;
alter table public.medical_profiles enable row level security;
alter table public.groups enable row level security;
alter table public.young_people_groups enable row level security;
alter table public.events enable row level security;
alter table public.attendance enable row level security;
alter table public.alert_rules enable row level security;
alter table public.alerts enable row level security;
alter table public.followups enable row level security;
alter table public.projects enable row level security;
alter table public.project_tasks enable row level security;
alter table public.task_assignees enable row level security;
alter table public.push_devices enable row level security;
alter table public.notifications enable row level security;
alter table public.audit_log enable row level security;

create policy "users read self admins read all" on public.app_users for select to authenticated using(id=auth.uid() or public.has_role(array['superadmin','admin']::public.app_role[]));
create policy "admins manage app users" on public.app_users for all to authenticated using(public.has_role(array['superadmin','admin']::public.app_role[])) with check(public.has_role(array['superadmin','admin']::public.app_role[]));
create policy "staff read youth" on public.young_people for select to authenticated using(public.has_role(array['superadmin','admin','leader','instructor']::public.app_role[]));
create policy "authorized write youth" on public.young_people for all to authenticated using(public.has_permission('youth.write')) with check(public.has_permission('youth.write'));
create policy "staff read guardians" on public.guardians for select to authenticated using(public.has_role(array['superadmin','admin','leader']::public.app_role[]));
create policy "authorized write guardians" on public.guardians for all to authenticated using(public.has_permission('youth.write')) with check(public.has_permission('youth.write'));
create policy "staff read guardian links" on public.young_person_guardians for select to authenticated using(true);
create policy "authorized write guardian links" on public.young_person_guardians for all to authenticated using(public.has_permission('youth.write')) with check(public.has_permission('youth.write'));
create policy "medical read explicit" on public.medical_profiles for select to authenticated using(public.has_permission('medical.read'));
create policy "medical write explicit" on public.medical_profiles for all to authenticated using(public.has_permission('medical.write')) with check(public.has_permission('medical.write'));
create policy "staff read groups" on public.groups for select to authenticated using(true);
create policy "admin manage groups" on public.groups for all to authenticated using(public.has_role(array['superadmin','admin']::public.app_role[])) with check(public.has_role(array['superadmin','admin']::public.app_role[]));
create policy "staff read youth groups" on public.young_people_groups for select to authenticated using(true);
create policy "authorized manage youth groups" on public.young_people_groups for all to authenticated using(public.has_permission('youth.write')) with check(public.has_permission('youth.write'));
create policy "staff read events" on public.events for select to authenticated using(true);
create policy "authorized manage events" on public.events for all to authenticated using(public.has_permission('events.write')) with check(public.has_permission('events.write'));
create policy "staff read attendance" on public.attendance for select to authenticated using(true);
create policy "authorized insert attendance" on public.attendance for insert to authenticated with check(public.has_permission('attendance.write'));
create policy "authorized update attendance" on public.attendance for update to authenticated using(public.has_permission('attendance.write')) with check(public.has_permission('attendance.write'));
create policy "admin delete attendance" on public.attendance for delete to authenticated using(public.has_role(array['superadmin','admin']::public.app_role[]));
create policy "staff read alert rules" on public.alert_rules for select to authenticated using(true);
create policy "admin manage alert rules" on public.alert_rules for all to authenticated using(public.has_role(array['superadmin','admin']::public.app_role[])) with check(public.has_role(array['superadmin','admin']::public.app_role[]));
create policy "staff read alerts" on public.alerts for select to authenticated using(true);
create policy "leaders manage alerts" on public.alerts for all to authenticated using(public.has_role(array['superadmin','admin','leader']::public.app_role[])) with check(public.has_role(array['superadmin','admin','leader']::public.app_role[]));
create policy "staff read followups" on public.followups for select to authenticated using(true);
create policy "leaders manage followups" on public.followups for all to authenticated using(public.has_role(array['superadmin','admin','leader']::public.app_role[])) with check(public.has_role(array['superadmin','admin','leader']::public.app_role[]));
create policy "staff read projects" on public.projects for select to authenticated using(true);
create policy "authorized manage projects" on public.projects for all to authenticated using(public.has_permission('projects.write')) with check(public.has_permission('projects.write'));
create policy "staff read tasks" on public.project_tasks for select to authenticated using(true);
create policy "authorized manage tasks" on public.project_tasks for all to authenticated using(public.has_permission('projects.write')) with check(public.has_permission('projects.write'));
create policy "staff read task assignees" on public.task_assignees for select to authenticated using(true);
create policy "authorized manage task assignees" on public.task_assignees for all to authenticated using(public.has_permission('projects.write')) with check(public.has_permission('projects.write'));
create policy "own push devices" on public.push_devices for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "read targeted notifications" on public.notifications for select to authenticated using(target_user_id is null or target_user_id=auth.uid() or target_role=(select role from public.app_users where id=auth.uid()));
create policy "admins send notifications" on public.notifications for insert to authenticated with check(public.has_role(array['superadmin','admin']::public.app_role[]));
create policy "admins read audit" on public.audit_log for select to authenticated using(public.has_role(array['superadmin','admin']::public.app_role[]));
